# Create Tensors and perform basic operations with tensors

Description: This program demonstrates how to create and perform basic operations on tensors using NumPy. It starts by creating a 2D tensor and then performs element-wise operations such as multiplication, addition, and exponentiation. It also includes a transpose operation to rearrange the tensor's dimensions. These operations illustrate fundamental tensor manipulations commonly used in fields like machine learning, physics, and data science, where tensors are used to represent and process multi-dimensional data.

In [1]:
import numpy as np

t = np.array([[1, 2, 3], [4, 5, 6]])
t1 = t * 2
print(" \n",t1)

# Element-wise addition
t2 = t + 3
print(" \n" , t2)

# Element-wise exponentiation
t3 = np.power(t, 2)

# Transpose
print(" \n" ,t3)

t4 = np.transpose(t)
print(" \n" ,t4)

 
 [[ 2  4  6]
 [ 8 10 12]]
 
 [[4 5 6]
 [7 8 9]]
 
 [[ 1  4  9]
 [16 25 36]]
 
 [[1 4]
 [2 5]
 [3 6]]


# Create Tensors and apply split & merge operations and statistics operations

Description: This Python program allows users to create a tensor by defining its dimensions and entering values, then perform split and merge operations along specified axes (rows or columns) using the numpy library. The program splits the tensor into two parts and then merges them back together, displaying the results at each step. It provides a hands-on demonstration of basic tensor manipulation, useful for learning tensor operations in numpy.

In [2]:
import numpy as np

# Get user input for tensor dimensions
rows = int(input("Enter number of rows: "))
cols = int(input("Enter number of columns: "))

# Create an empty tensor with the specified dimensions
tensor = np.empty((rows, cols))

# Get user input for tensor values
for i in range(rows):
  for j in range(cols):
    tensor[i][j] = float(input(f"Enter value for [{i}][{j}]: "))

# Print the tensor
print("Original Tensor:\n", tensor)



# Get user input for split axis
split_axis = int(input("Enter the axis to split along (0 for rows, 1 for columns): "))

# Split the tensor along the specified axis
tensor_split = np.split(tensor, 2, axis=split_axis)
# Print the split tensors
print("Split tensors:\n", tensor_split)

# Merge the split tensors along the same axis
tensor_merged = np.concatenate(tensor_split, axis=split_axis)
# Print the merged tensor
print("Merged tensor:\n", tensor_merged)

mean=np.mean(tensor)
print("Mean:",mean)

std=np.std(tensor)
print("Standard Deviation:",std)

var=np.var(tensor)
print("Variance:",var)

max_val=np.max(tensor)
print("Maximum Value:",max_val)

min_val=np.min(tensor)
print("Minimum Value:",min_val)

reshaped_tensor = np.reshape(tensor, (1, -1))
print("Reshaped Tensor:\n", reshaped_tensor)

transposed_tensor = np.transpose(tensor)
print("Transposed Tensor:\n", transposed_tensor)

dot_product = np.dot(tensor, transposed_tensor)
print("Dot Product:\n", dot_product)

Enter number of rows: 2
Enter number of columns: 2
Enter value for [0][0]: 1
Enter value for [0][1]: 2
Enter value for [1][0]: 3
Enter value for [1][1]: 4
Original Tensor:
 [[1. 2.]
 [3. 4.]]
Enter the axis to split along (0 for rows, 1 for columns): 0
Split tensors:
 [array([[1., 2.]]), array([[3., 4.]])]
Merged tensor:
 [[1. 2.]
 [3. 4.]]
Mean: 2.5
Standard Deviation: 1.118033988749895
Variance: 1.25
Maximum Value: 4.0
Minimum Value: 1.0
Reshaped Tensor:
 [[1. 2. 3. 4.]]
Transposed Tensor:
 [[1. 3.]
 [2. 4.]]
Dot Product:
 [[ 5. 11.]
 [11. 25.]]
